spots = {
    "Agartala": ["Ujjayanta Palace", "Neermahal Water Palace", "Jagannath Temple", "Tripura Sundari Temple", "Heritage Park", "Venuban Vihar", "Sepahijala Wildlife Sanctuary", "Dumboor Lake"],
    "Agra": ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Itmad-ud-Daula's Tomb", "Mehtab Bagh", "Jama Masjid", "Ram Bagh", "Chini Ka Rauza"],
    "Ahmedabad": ["Sabarmati Ashram", "Jama Masjid", "Kankaria Lake", "Adalaj Stepwell", "Sidi Saiyyed Mosque", "Akshardham Temple", "Sabarmati Riverfront", "Sarkhej Roza"],
    "Allahabad": ["Triveni Sangam", "Allahabad Fort", "Khusro Bagh", "Anand Bhavan", "All Saints Cathedral", "Allahabad Museum", "Chandra Shekhar Azad Park", "Mayo Memorial Hall"],
    "Amritsar": ["Golden Temple", "Jallianwala Bagh", "Wagah Border", "Durgiana Temple", "Maharaja Ranjit Singh Museum", "Partition Museum", "Gobindgarh Fort", "Tarn Taran Sahib"],
    "Aurangabad": ["Ajanta Caves", "Ellora Caves", "Bibi Ka Maqbara", "Daulatabad Fort", "Aurangabad Caves", "Panchakki", "Ghrishneshwar Temple", "Pitalkhora Caves"],
    "Bagdogra": ["Siliguri", "Darjeeling", "Gangtok", "Kalimpong", "Mirik", "Tiger Hill", "Batasia Loop", "Peace Pagoda"],
    "Bengaluru": ["Lalbagh Botanical Garden", "Bangalore Palace", "Cubbon Park", "ISKCON Temple", "Bannerghatta National Park", "Wonderla Amusement Park", "Vidhana Soudha", "Tipu Sultan's Summer Palace"],
    "Bhopal": ["Upper Lake", "Bhimbetka Rock Shelters", "Van Vihar National Park", "Gohar Mahal", "Bharat Bhavan", "Shaukat Mahal", "Lower Lake", "Rani Kamlapati Palace"],
    "Bhubaneswar": ["Lingaraja Temple", "Udayagiri and Khandagiri Caves", "Nandankanan Zoological Park", "Dhauli Shanti Stupa", "Rajarani Temple", "Mukteshwar Temple", "Odisha State Museum", "Ram Mandir"],
    "Bhuj": ["White Desert", "Kutch Museum", "Mandvi Beach", "Aina Mahal", "Prag Mahal", "Vijay Vilas Palace", "Hodka Village", "Black Hill"],
    "Chandigarh": ["Rock Garden", "Sukhna Lake", "Rose Garden", "Pinjore Gardens", "Chandigarh Capitol Complex", "Terraced Garden", "Butterfly Park", "Leisure Valley"],
    "Chennai": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "San Thome Basilica", "Arignar Anna Zoological Park", "Government Museum", "Guindy National Park", "Vivekananda House"],
    "Coimbatore": ["Dhyanalinga Temple", "Marudhamalai Hill Temple", "Monkey Falls", "Siruvani Waterfalls", "Velliangiri Mountains", "Eachanari Vinayagar Temple", "Anamalai Tiger Reserve", "Black Thunder Theme Park"],
    "Dehradun": ["Robber's Cave", "Sahastradhara", "Tapkeshwar Temple", "Malsi Deer Park", "Bhatta Falls", "Rajaji National Park", "Lacchiwala", "Clock Tower"],
    "Delhi": ["Red Fort", "Qutub Minar", "India Gate", "Lotus Temple", "Humayun's Tomb", "Akshardham Temple", "Gurudwara Bangla Sahib", "National Zoological Park"],
    "Dibrugarh": ["Dibru-Saikhowa National Park", "Radha Krishna Mandir", "Chakrashila Wildlife Sanctuary", "Dinjoy Satra", "Jeypore Rainforest", "Brahmaputra River", "Jokai Botanical Garden", "Srimanta Sankaradeva Van Udyan"],
    "Dimapur": ["Kachari Ruins", "Triple Falls", "Zoological Park", "Dimapur Jain Temple", "Rangapahar Reserve Forest", "Shiva Temple", "Diezephe Craft Village", "Rangapahar Reserve Forest"],
    "Goa": ["Basilica of Bom Jesus", "Calangute Beach", "Dudhsagar Falls", "Fort Aguada", "Anjuna Beach", "Colva Beach", "Chapora Fort", "Se Cathedral"],
    "Guwahati": ["Kamakhya Temple", "Assam State Zoo", "Umananda Island", "Pobitora Wildlife Sanctuary", "Navagraha Temple", "Brahmaputra River Cruise", "Srimanta Sankardev Kalakshetra", "Guwahati Planetarium"],
    "Hyderabad": ["Charminar", "Golconda Fort", "Hussain Sagar Lake", "Ramoji Film City", "Salar Jung Museum", "Nehru Zoological Park", "Chowmahalla Palace", "Lumbini Park"],
    "Imphal": ["Kangla Fort", "Manipur Zoological Gardens", "Shree Govindajee Temple", "Loktak Lake", "Ima Keithel Women's Market", "Khonghampat Orchidarium", "Sekta Archaeological Living Museum", "Shaheed Minar"],
    "Indore": ["Rajwada Palace", "Sarafa Bazaar", "Kanch Mandir", "Patalpani Waterfall", "Lal Bagh Palace", "Annapurna Temple", "Indore Museum", "Krishnapura Chhatris"],
    "Jaipur": ["Hawa Mahal", "Amber Fort", "City Palace", "Jantar Mantar", "Albert Hall Museum", "Nahargarh Fort", "Jaigarh Fort", "Birla Mandir"],
    "Jammu": ["Vaishno Devi Temple", "Raghunath Temple", "Amar Mahal Palace", "Bagh-e-Bahu", "Peer Kho Cave Temple", "Bahu Fort", "Mubarak Mandi Palace", "Shiv Khori Cave Temple"],
    "Jodhpur": ["Mehrangarh Fort", "Jaswant Thada", "Umaid Bhawan Palace", "Mandore Gardens", "Ghanta Ghar", "Rao Jodha Desert Rock Park", "Machiya Safari Park", "Sardar Government Museum"],
    "Kochi": ["Fort Kochi", "Mattancherry Palace", "Jewish Synagogue", "Chinese Fishing Nets", "Santa Cruz Basilica", "Marine Drive", "Bolgatty Palace", "Hill Palace Museum"],
    "Kolkata": ["Victoria Memorial", "Howrah Bridge", "Indian Museum", "Dakshineswar Kali Temple", "Belur Math", "Eden Gardens", "Mother House", "Science City"],
    "Kozhikode": ["Kozhikode Beach", "Beypore Beach", "Mananchira Square", "Kappad Beach", "Thusharagiri Waterfalls", "Kadalundi Bird Sanctuary", "Kakkayam Dam", "Kozhippara Falls"],
    "Lucknow": ["Bara Imambara", "Chota Imambara", "Rumi Darwaza", "Ambedkar Memorial Park", "Hazratganj", "British Residency", "Janeshwar Mishra Park", "Lucknow Zoo"],
    "Madurai": ["Meenakshi Amman Temple", "Thirumalai Nayakkar Mahal", "Gandhi Memorial Museum", "Alagar Koil", "Vandiyur Mariamman Teppakulam", "Koodal Azhagar Temple", "Thiruparankundram Murugan Temple", "Athisayam Water Amusement Park"],
    "Mangalore": ["Kadri Manjunath Temple", "Panambur Beach", "Tannirbhavi Beach", "St. Aloysius Chapel", "Sultan Battery", "Pilikula Nisargadhama", "Mangaladevi Temple", "Ullal Beach"],
    "Mumbai": ["Gateway of India", "Marine Drive", "Siddhivinayak Temple", "Haji Ali Dargah", "Elephanta Caves", "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya", "Juhu Beach", "Film City"],
    "Nagpur": ["Deekshabhoomi", "Futala Lake", "Raman Science Centre", "Seminary Hill", "Ambazari Lake and Garden", "Maharaj Baug and Zoo", "Shukrawari Lake", "Japanese Rose Garden"],
    "Patna": ["Golghar", "Patna Museum", "Agam Kuan", "Bihar Museum", "Takht Sri Patna Sahib", "Sanjay Gandhi Jaivik Udyan", "Eco Park", "Mahavir Mandir"],
    "Port Blair": ["Cellular Jail", "Radhanagar Beach", "Ross Island", "North Bay Island", "Jolly Buoy Island", "Viper Island", "Mount Harriet National Park", "Chidiya Tapu"],
    "Pune": ["Shaniwar Wada", "Aga Khan Palace", "Sinhagad Fort", "Raja Dinkar Kelkar Museum", "Dagadusheth Halwai Ganapati Temple", "Parvati Hill", "Lal Mahal", "Saras Baug"],
    "Raipur": ["Nandan Van Zoo and Safari", "Vivekananda Sarovar", "Mahant Ghasidas Museum", "Gandhi Udyan Park", "Purkhouti Muktangan", "Kutchery Chowk", "Ambuja City Centre", "ISKCON Raipur, Sri Sri Radha Rasbihari Temple"],
    "Rajkot": ["Watson Museum", "Aji Dam", "Rampara Wildlife Sanctuary", "Nyari Dam", "Kaba Gandhi No Delo", "Rashtriya Shala", "Khambhalida Caves", "Race Course Grounds"],
    "Ranchi": ["Rock Garden", "Hundru Falls", "Panch Gagh Falls", "Hirni Falls", "Jonha Falls", "Birsa Zoological Park", "Patratu Valley", "Deer Park"],
    "Srinagar": ["Dal Lake", "Shalimar Bagh", "Nishat Bagh", "Pari Mahal", "Jamia Masjid", "Shankaracharya Temple", "Indira Gandhi Memorial Tulip Garden", "Hazratbal Shrine"],
    "Surat": ["Dumas Beach", "Sardar Patel Museum", "Sarthana Nature Park", "Suvali Beach", "Ambika Niketan Temple", "Jagdishchandra Bose Aquarium", "VR Surat", "Chintamani Jain Temple"],
    "Tiruchirappalli": ["Rockfort Temple", "Sri Ranganathaswamy Temple", "Srirangam Island", "Jambukeswarar Temple", "Kallanai Dam", "Government Museum", "St. Joseph's Church", "Puliyancholai Waterfalls"],
    "Trivandrum": ["Padmanabhaswamy Temple", "Kovalam Beach", "Napier Museum", "Poovar Island", "Shankumugham Beach", "Vizhinjam Lighthouse", "Sree Chithra Art Gallery", "Agastya Mala"],
    "Udaipur": ["City Palace", "Lake Pichola", "Jag Mandir", "Saheliyon-ki-Bari", "Jagdish Temple", "Fateh Sagar Lake", "Sajjangarh Palace", "Vintage Car Museum"],
    "Vadodara": ["Laxmi Vilas Palace", "Sayaji Baug", "Kirti Mandir", "Sursagar Lake", "Baroda Museum and Picture Gallery", "EME Temple", "Vadodara Central Library", "Maharaja Fateh Singh Museum"],
    "Varanasi": ["Kashi Vishwanath Temple", "Dashashwamedh Ghat", "Assi Ghat", "Sarnath", "Manikarnika Ghat", "Tulsi Manas Temple", "Durga Temple", "Bharat Mata Mandir"],
    "Visakhapatnam": ["Rama Krishna Beach", "INS Kurusura Submarine Museum", "Kailasagiri", "Yarada Beach", "Simhachalam Temple", "VUDA Park", "Borra Caves", "Dolphin's Nose"]
}
